### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by Bogdan107** [xrmx/bootchart#92]
Gentoo,
app-benchmarks/bootchart2  v0.14.8-r1
python 3.9

```
> pybootchartgui
Traceback (most recent call last):
  File "/usr/bin/pybootchartgui", line 20, in <module>
    from pybootchartgui.main import main
  File "/usr/lib/python3.9/site-packages/pybootchartgui/main.py", line 25, in <module>
    from . import parsing
  File "/usr/lib/python3.9/site-packages/pybootchartgui/parsing.py", line 26, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Comment by xrmx** [comment]
Hi, tt has already been fixed in 0.14.9, ask gentoo to upgrade.
